name: Continuous Integration

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit                                                
  
      - name: Run pre-commit
        run: |
          pre-commit run --all-files || { echo "Pre-commit failed, showing diff:"; git diff; exit 1; }

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.13]  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox
          pip install .[test]

      - name: Run tests
        run: |
          nox -s tests || { echo "Tests failed"; exit 1; }

